language: php
dist: trusty
sudo: false

matrix:
  include:
    - php: "5.2"
      dist: precise
      env: PHP52SUCKS=true
    - php: "5.3"
      dist: precise
    - php: "5.4"
    - php: "5.5"
    - php: "5.6"
    - php: "7.0"
    - php: "7.1"
    - php: "7.2"
    - php: "7.3"

install:
  - |
    if [[ $PHP52SUCKS == true ]]; then
      wget http://download.pear.php.net/package/HTML_Common2-2.1.1.tgz
      pear install ./HTML_Common2-2.1.1.tgz
    else
      pear channel-update pear.php.net
      pear install HTML_Common2
      composer install
    fi
script:
  - |
    if [[ $PHP52SUCKS == true]]; then
      phpunit tests
    else
      ./vendor/bin/phpunit tests
    fi
