language: php
dist: trusty
sudo: false

matrix:
  include:
    - php: "5.2"
      dist: precise
      env: SKIPCOMPOSER=true
    - php: "5.3"
      dist: precise
    - php: "5.4"
    - php: "5.5"
    - php: "5.6"
    - php: "7.0"
    - php: "7.1"
    - php: "7.2"

install:
  - pear channel-update pear.php.net
  - pear install HTML_Common2
  - if [[ $SKIPCOMPOSER != true ]]; then composer install; fi
script:
  - if [[ $SKIPCOMPOSER == true ]]; then phpunit tests; fi
  - if [[ $SKIPCOMPOSER != true ]]; then ./vendor/bin/phpunit tests; fi
